version: '3'
services:
  thing-provider-service:
    image: node
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: bash -c "npm install && node --inspect-brk=0.0.0.0 ./bin/server.js"
    ports:
      - "3002:3002"
      - "9229:9229"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

networks:
  default:
    external:
      name: thing-provider-local-network
